### ISSUE TITLE
Raycast intersect with everything on the first frame

### ISSUE THREAD

**Issue by markaren** [markaren/three.kt#45]

**Comment by Displee** [comment]
Mind elaborating this issue. Is the bug that it doesn't intersect on the first frame?

**Comment by markaren** [comment]
From what I remember it reports that it _does_ intersect with everything on the very first frame.

**Comment by Displee** [comment]
Ah, alright.

**Comment by markaren** [comment]
This does not actually seems to be an issue. Also mouse coordinates should be set to `val mouse = Vector2(-1, -1)` in order to not hit objects with position.ZERO
