### ISSUE TITLE
Revert back to JVM only project

### ISSUE THREAD

**Issue by markaren** [markaren/three.kt#49]
I need to be selfish about this one. Currently this project has been setup as a Kotlin multiplatform project with JVM being the only implementation. The idea was that JS and Native would follow. I thought that sounded like a good idea and the initial JVM only project was converted into a multiplatform project. 

I fell this change has not been beneficial for me since I'm only interested in the JVM target and the change made it harder to develop that. Therefore I will revert back to JVM only. If someone wants multi-platform, they'll need to fork this project. 

Sorry, @Dominaezzz and @altavir, perhaps you can team up for a continued multiplatform project.

**Comment by Dominaezzz** [comment]
Can you outline anything in particular that is getting in your way?

**Comment by markaren** [comment]
It's a collection of smaller things. The main point is that I don't have the luxury of time anymore. Multi-platform requires more though and time. It also requires collaboration with JS/Native.
But some issues are: I'm still not confident with the kotlin DSL yet. Multi-platform tests don't seem to be working and Java is unusable from the example project due to IntelliJ not being able to import the multi-platform classes. At least on this system.

**Comment by altavir** [comment]
Sadly, I do not have time to contribute to this project as well for now. Currently, I just use my own fork of JS version. I can later contribute it with some corrections or even adapt it to API changes here.

**Comment by markaren** [comment]
Putting this to rest for the time being.
