### ISSUE TITLE
Any plans for Three.VideoTexture and CanvasTexture?

### ISSUE THREAD

**Issue by devdivr** [markaren/three.kt#52]
Hello,
I'm really interested in your project to convert three.js to kotlin. I want to support you guys to keep going to implement it.
One question is that are you going to convert Three.VideoTexture and CanvasTexture to kotlin?

Really appreciate it if you leave an answer.
Thank you

**Comment by markaren** [comment]
> One question is that are you going to convert Three.VideoTexture and CanvasTexture to kotlin?

This project is kinda dormant from my side atm. I have no plans of implementing what you ask, nor have I gotten any hints that anyone else is doing or want to do it.

Happy to receive a PR!

**Comment by devdivr** [comment]
Ok. Thanks for the answer!
