### ISSUE TITLE
Support MacOS development out of the box

### ISSUE THREAD

**Issue by arocnies** [markaren/three.kt#6]
The LWJGL natives from the build.gradle target windows. It would be nice to have an easy way to build and test Three.kt from MacOS without requiring edits to the build.gradle.

**Comment by markaren** [comment]
Sure thing. For some reason the lwjgl customizer only generates artifacts for one platform. But I can add more manually.

**Comment by markaren** [comment]
Okey, what I said was not true. I will add a fix asap

**Comment by arocnies** [comment]
@markaren Looks good for assembling 👍 
The larger `Test` fails on Mac but I can open a separate issue for that.
