### ISSUE TITLE
Upload to maven central

### ISSUE THREAD

**Issue by Displee** [markaren/three.kt#61]
Upload this awesome project to maven central so we can easily use it in our projects.

**Comment by markaren** [comment]
IMO it's good enough to have it available though bintray (which it already it is). As a user, it's just a matter of adding an additional repository. Which is a one-liner for gradle users `maven { url "https://dl.bintray.com/laht/mvn" }`

**Comment by Displee** [comment]
Ah, I didn't notice it was available on bintray. Maybe you could add that to the README or something. Thanks. You may close this if you want.

**Comment by markaren** [comment]
This is the Bintray thing in the README:
![image](https://user-images.githubusercontent.com/6005031/93666434-7725a300-fa7e-11ea-9e30-1448beb25ee5.png)

I agree that it could be overlooked /misunderstood. Will figure out something.

**Comment by markaren** [comment]
Added some more info to README

**Comment by Displee** [comment]
Ah! I'm not familiar with Bintray so that's probably why I overlooked it xD. Thanks again.
