### ISSUE TITLE
Can't implement mouse events in `PeripheralsEventSource`

### ISSUE THREAD

**Issue by Displee** [markaren/three.kt#62]
I want to set a custom `PeripheralsEventSource` for my orbit controls, but I can't create a new mouse event. One method there is internal and all the setters are private.

Allow us to implement our own `PeripheralsEventSource` please. I only want to enable `OrbitControls` within my `cuchaz.jfxgl.controls.OpenGLPane`.

**Comment by markaren** [comment]
Will update `MouseEvent` to accommodate this
