### ISSUE TITLE
Bintray is shutting down -> find replacement

### ISSUE THREAD

**Issue by markaren** [markaren/three.kt#70]

**Comment by Displee** [comment]
I personally use Nexus: https://oss.sonatype.org/#welcome

After uploading, it takes about 5 minutes to sync with Maven (from my experience).

**Comment by markaren** [comment]
I used sonatype a little in the past, but I found it cumbersome. I thought I could use github packages, but for some reason they require users to authenticate against github. So that is a no go. The solution I go for will be used for a handful of other projects as well.

**Comment by Displee** [comment]
Oh really, oh well, I use https://repsy.io/ for private repos. It also supports public repos though. Works basically same as Bintary in terms of implementation. Just add this url:
```
maven(url = "https://repo.repsy.io/mvn/yourrepo")
```

**Comment by Displee** [comment]
Their control panel is also amazingly simple too.
